services:
  lvs-router:
    container_name: lvs-router
    image: lvs-router:latest
    pull_policy: never
    platform: linux/amd64
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: host
    volumes:
      - ./docker/volumes/config/lvs-router.env:/opt/lvs-router/lvs-router.env
      - ./docker/volumes/config/keepalived:/opt/lvs-router/keepalived
      - /lib/modules:/lib/modules:ro
