services:
  lb1:
    image: lvs-router-lb:lb1
    platform: linux/amd64
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: host
    environment:
      HEALTHY_HTTP_PORT: "45555"
    volumes:
      - ./keepalived:/etc/keepalived:ro
      - /lib/modules:/lib/modules:ro
  lb2:
    image: lvs-router-lb:lb2
    platform: linux/amd64
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: host
    environment:
      HEALTHY_HTTP_PORT: "45555"
    volumes:
      - ./keepalived:/etc/keepalived:ro
      - /lib/modules:/lib/modules:ro
