virtual_server 172.17.64.159 45555 {
    delay_loop 6
    lb_algo sh
    lb_kind DR
    protocol TCP

    real_server 172.17.64.129 45555 {
        weight 1
        TCP_CHECK {
            connect_port 45555
            connect_timeout 3
            retry 1
            delay_before_retry 1
        }
    }
    real_server 172.17.64.128 45555 {
        weight 1
        TCP_CHECK {
            connect_port 45555
            connect_timeout 3
            retry 1
            delay_before_retry 1
        }
    }
    real_server 172.17.64.127 45555 {
        weight 1
        TCP_CHECK {
            connect_port 45555
            connect_timeout 3
            retry 1
            delay_before_retry 1
        }
    }
    real_server 172.17.64.126 45555 {
        weight 1
        TCP_CHECK {
            connect_port 45555
            connect_timeout 3
            retry 1
            delay_before_retry 1
        }
    }
}
