global_defs {
    router_id LB1
}

vrrp_instance VI_1 {
    state MASTER
    interface ens18
    virtual_router_id 1
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        172.17.64.149/32 dev ens18 label ens18:vip
    }
    notify_master "/opt/lvs-router/bin/ipvs-state.sh master"
    notify_backup "/opt/lvs-router/bin/ipvs-state.sh backup"
    notify_fault "/opt/lvs-router/bin/ipvs-state.sh fault"
}
